### ISSUE TITLE
Adding a user - Weird looping error

### ISSUE THREAD

**Issue by mikekenn** [ThreeFourSeven/Database-Gui#22]
When we go to create a user some unusual things happen, and i think it might be because the update function is a huge loop.

Firstly, the user gets created in the DB - Added the easter bunny.
`SQL> SELECT *
  2  FROM users;

        ID FIRST_NAME           LAST_NAME            USERNAME   EMAIL                                              PASSWORD HIPAA_AUTHORIZED
---------- -------------------- -------------------- ---------- -------------------------------------------------- -------- ----------------
         1 Michael              Kennedy              mkennedy   mkennedy@jsdb.com                                  csci275                 1
         2 Darwin               Groskleg             dgroskleg  dgroskleg@jsdb.com                                 csci275                 0
       107 joe                  doe                  jdoe       jdoe@jsdb.com                                      pass123                 0
         4 Cynthia              Forgeron             cforgeron  cfougeron@jsdb.com                                 csci275                 0
         5 Martin               vanBommel            mvanbommel mvanbommel@jsdb.com                                csci275                 0
         6 Jacob                Levman               jlevman    jlevman@jsdb.com                                   csci275                 1
       117 easter               bunny                ebunny     ebunny@jsdb.com                                    easter12                0
         3 Seven                Randall              srandall   srandell@jsdb.com                                  csci275                 1

8 rows selected.`

Secondly, we get this ugly looping error.
`
java.sql.SQLIntegrityConstraintViolationException: ORA-00001: unique constraint (JSDB.SYS_C0076300) violated
ORA-06512: at line 4

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:494)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:446)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1054)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:623)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:252)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:612)
	at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:223)
	at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:56)
	at oracle.jdbc.driver.T4CCallableStatement.executeForRows(T4CCallableStatement.java:907)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1119)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3780)
	at oracle.jdbc.driver.T4CCallableStatement.executeInternal(T4CCallableStatement.java:1300)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3887)
	at oracle.jdbc.driver.OracleCallableStatement.execute(OracleCallableStatement.java:4230)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1079)
	at adapters.DBAdapter.executeCall(DBAdapter.java:116)
	at models.UserModel.create(UserModel.java:102)
	at game.GameManager.update(GameManager.java:190)
	at engine.GameContainer.run(GameContainer.java:65)
	at java.lang.Thread.run(Unknown Source)
	at engine.GameContainer.start(GameContainer.java:30)
	at game.GameManager.main(GameManager.java:311)
Caused by: Error : 1, Position : 0, Sql = DECLARE 
  rec_id NUMBER; 
BEGIN 
  INSERT INTO users 
    (first_name, last_name, username, email, password, hipaa_authorized) 
    VALUES 
    ('easter', 'bunny', 'ebunny', 'ebunny@jsdb.com', 'easter12', 0)
    RETURNING id INTO rec_id; 
  :1  := rec_id; 
END; 
, OriginalSql = DECLARE 
  rec_id NUMBER; 
BEGIN 
  INSERT INTO users 
    (first_name, last_name, username, email, password, hipaa_authorized) 
    VALUES 
    ('easter', 'bunny', 'ebunny', 'ebunny@jsdb.com', 'easter12', 0)
    RETURNING id INTO rec_id; 
  ? := rec_id; 
END; 
, Error Msg = ORA-00001: unique constraint (JSDB.SYS_C0076300) violated
ORA-06512: at line 4

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:498)
	... 21 more
`

Im pretty sure this is caused because of the update loop, for some reason it is holding onto the information that the user input and it just looping through creating the user, and since the first add works you get an error that says that ID already exits with the name/username/email ... blah blah blah.

**Comment by mikekenn** [comment]
Is there a way to call this function outside of the update loop so that it only can be called once?

**Comment by mikekenn** [comment]
The issue has been corrected. @ThreeFourSeven fixed it.
